version: "3.3"  # optional since v1.27.0
services:
  crystaline_1:
    image : crystaline-docker
    ports:
      - "5001:5000"
    networks:
      - bridge1
  crystaline_2:
    image : crystaline-docker
    ports:
      - "5002:5000"
    networks:
      - bridge1
      - bridge2
  crystaline_3:
    image : crystaline-docker
    ports:
      - "5003:5000"
    networks:
      - bridge2
      - bridge3
  crystaline_4:
    image : crystaline-docker
    ports:
      - "5004:5000"
    networks:
      - bridge3
  crystaline_5:
    image : crystaline-docker
    ports:
      - "5005:5000"
    networks:
      - bridge3
      - bridge1
networks:
  bridge1:
    driver: bridge
  bridge2:
    driver: bridge
  bridge3:
    driver: bridge