version: "3.3"  # optional since v1.27.0
services:
  crystalline_1:
    image : crystalline-docker
    ports:
      - "5001:5002"
    networks:
      - bridge1
  crystalline_2:
    image : crystalline-docker
    ports:
      - "5002:5002"
    networks:
      - bridge1
      - bridge2
  crystalline_3:
    image : crystalline-docker
    ports:
      - "5003:5002"
    networks:
      - bridge2
      - bridge3
  crystalline_4:
    image : crystalline-docker
    ports:
      - "5004:5002"
    networks:
      - bridge3
  crystalline_5:
    image : crystalline-docker
    ports:
      - "5005:5002"
    networks:
      - bridge3
      - bridge1
networks:
  bridge1:
    driver: bridge
  bridge2:
    driver: bridge
  bridge3:
    driver: bridge